M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Thứ năm, 01 Tháng 2 Năm 2024 23:34:02 +07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-01T23:34:02+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X3.4296Y-5.451
X3.4796Y-3.551
X5.4796Y-4.151
M30
