/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 29-Apr-2023 08:40:28 */
/* MATLAB Version: 9.11.0.1769968 (R2021b) */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef _FUZZY_TUNING_PID_H_
#define _FUZZY_TUNING_PID_H_

#include "main.h"
#include <stdlib.h>

#ifdef __cplusplus
    extern "C" {
#endif

struct fuzzy_tuning;
typedef struct fuzzy_tuning fuzzy_tuning_t;

struct fuzzy_tuning
{
    float angle;
    void (*set_tuning)(fuzzy_tuning_t * const fuzzy_tuning_p);
};

/**********************
 *     OPERATION
 **********************/

fuzzy_tuning_t *FUZZY_TUNING_Create();
void FUZZY_TUNING_Destroy(fuzzy_tuning_t *const fuzzy_tuning_p);

#ifdef __cplusplus
    }
#endif

#endif
